# Site
name: 'Megazone DSG WebService Blog'
logo: '/assets/img/logo.png'
favicon: '/assets/img/favicon.ico'
baseurl: ''
disqus: 'megazone-tech-blog-1'
email: 'seungpilpark@mz.co.kr'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

  seungpilpark:
    name: 박승필
    bio: 배우는걸 좋아하는 사람입니다.
    avatar: "/assets/authors/seungpilpark.jpeg"
    email: seungpilpark@mz.co.kr
    github_username: SeungpilPark
    facebook_username: mz.sppark

  soda1127:
    name: 이기정
    bio: 사회공헌을 위한 개발을 좋아합니다. 최근엔 안드로이드 플랫폼을 기반으로하는 Reactive Programing에 관심이 많습니다.
    avatar: "https://i.imgur.com/oGENDcZ.jpg"
    email: dlrlwjd1127@naver.com
    github_username: SODA1127
    facebook_username: soda1127

  sondayeon:
    name: 손다연
    bio: Cloud Native 개발자를 목표로 트레이닝 중입니다.
    avatar: "/assets/authors/dayeon.png"
    email: sondayeon@mz.co.kr
    github_username: it-dayeon
    facebook_username:

  byeongcheonmun:
    name: 문병천
    bio: 그냥저냥 이것저것 모아두는 습성을 가졌습니다.
    email: munbc@mz.co.kr
    github_username: munbc8308
    facebook_username:
    
  Lukoh:
    name: Lukoh
    bio: 모바일팀
    email: namkulho@mz.co.kr
    github_username: Lukoh-MZ
    facebook_username:
    linkedin_username: https://www.linkedin.com/in/lukoh-nam-68207941/
    
  MinjaeGhim:
    name: 김민재
    bio: 유능하고 싶은 개발자
    avatar: "/assets/authors/minjae.jpg"
    email: mjaek@mz.co.kr
    github_username: MinjaeGhim
    facebook_username:    

  youngjucha:
    name: 차영주
    bio: 모바일 개발자입니다.
    email: chayj@mz.co.kr
    github_username: youngjucha

  insupark83:
    name: 박인수
    bio: 배우는걸 좋아하는 개발자
    avatar: "/assets/authors/insupark.jpg"
    email: isp8373@naver.com
    github_username: insupark83
    facebook_username:

  HYGill:
    name: 길혜영
    bio: 이것저것 신기한건 다 해보고 싶은
    email: gilhyeyeong@mz.ci.kr
    github_username: HYGill
    
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: megazone
      avatar: /assets/img/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, .idea]
